### ISSUE TITLE
I cant get copy of your TWRP img

### ISSUE THREAD

**Issue by enescaglayan** [hak86/android_device_huawei_prague#1]
Hi, sorry but i am not good at using phones but i really want install TWRP to get root on to my PRA-LX1 phone. I found your thread at XDA-developers and i tried to install the twrp file but it said 404 Not Found. I found this project. I dont know how to get the TWRP img file but GitHub only allows me to get the ZIP file. I just want get one copy of the TWRP image

my suggestions:
-post releases

also i dont know how to root my phone using TWRP i mean you gave us supersu zip file to root ours phone but it says EMUI 5 but i have EMUI 8 if you could also help ne to root my phone it will be good

sorry because i writed this in phone(dont worry i have pc) also sorry if i am a phone noob.

**Comment by hak86** [comment]
@enescaglayan if you are looking for emui8's twrp here's one https://sourceforge.net/projects/p8-lite-2017/files/Emui-8.x/Recoveries/twrp-3.3.1.0-emui-8.x-prague-30072019.img/download
